### PR TITLE
Autogenerated markdown fixes

### PR DESCRIPTION
**Pull request by branfosj**
for https://github.com/easybuilders/easybuild-docs/pull/87

### CODE REVIEW

**Comment by boegel** [comment]
@branfosj Also run the script, and include the fixes `.md` files?

**Comment by branfosj** [comment]
> @branfosj Also run the script, and include the fixes `.md` files?

I'm getting more changes than I'm expecting:

```
git diff | wc -l
38824
```

**Comment by boegel** [comment]
Because you're also picking up on https://github.com/easybuilders/easybuild-framework/pull/4162?

There are some additional changes in `develop` of easyconfigs too (more software/versions), maybe that's part of it?

**Comment by branfosj** [comment]
> Because you're also picking up on [easybuilders/easybuild-framework#4162](https://github.com/easybuilders/easybuild-framework/pull/4162)?
> 
> There are some additional changes in `develop` of easyconfigs too (more software/versions), maybe that's part of it?

There are some differences caused by you running on a mac and me on linux. I've removed those. The supported software page (and most of the changes) was due to an issue with my setup meaning that I was looking at only a few easyconfigs.

There is an issue with `toolchain-opts.md`. I seem to have a lot fewer toolchains.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
